### ISSUE TITLE
Does not working in server mode in windows,

### ISSUE THREAD

**Issue by satyagadepalli** [mysamai/mysam#23]
I am not able to make work for checking What is the weather like in Berlin?

Is there any impact of below errors in installation?

E:\>npm install mysam -g
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> electron-prebuilt@0.36.12 postinstall C:\Users\xyz\AppData\Roaming\npm\node_modules\mysam\node_modules\electron-prebuilt
> node install.js

C:\Users\xyz\AppData\Roaming\npm\mysam -> C:\Users\xyz\AppData\Roaming\npm\node_modules\mysam\bin\mysam
mysam@0.1.3 C:\Users\xyz\AppData\Roaming\npm\node_modules\mysam
├── q@1.4.1
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── pos@0.1.9
├── debug@2.2.0 (ms@0.7.1)
├── lodash@3.10.1
├── feathers-memory@0.3.4 (feathers-errors@0.2.5, uberproto@1.1.2, lodash@2.4.2)
├── feathers-hooks@0.5.1 (feathers-commons@0.2.11, lodash@2.4.2)
├── body-parser@1.15.2 (bytes@2.4.0, content-type@1.0.2, depd@1.1.0, qs@6.2.0, on-finished@2.3.0, raw-body@2.1.7, http-errors@1.5.0, iconv-lite@0.4.13
, type-is@1.6.13)
├── natural-brain@0.2.3 (brain.js@0.7.0, natural@0.4.0)
├── feathers@1.3.0 (primus-emitter@3.1.1, feathers-errors@1.2.4, feathers-commons@0.3.4, rubberduck@1.1.0, uberproto@1.2.0, express@4.14.0, socket.io@
1.4.8, primus@4.0.5)
├── feathers-nedb@0.1.0 (uberproto@1.2.0, feathers-errors@0.2.5, nedb@1.8.0)
├── electron-prebuilt@0.36.12 (extract-zip@1.5.0, electron-download@2.1.2)
└── mysam-frontend@0.1.9 (feathers-client@0.1.3, assert@1.4.1, pos@0.3.0, animate.css@3.5.1, jquery@2.2.4, socket.io-client@1.4.8, canjs-feathers@0.2.
0, steal-mocha@0.0.3, can@2.3.0-pre.13, steal@0.11.4)

if i run >mysam --Develop, it shows some exceptions and javascript gets into chrome browser debugger

Potentially unhandled rejection [6] TypeError: Error loading "sam/index.stache!can@2.3.0-pre.13#view/stache/system" at <unknown>
Error loading "sam/index.stache!can@2.3.0-pre.13#view/stache/system" from "sam/app" at http://localhost:9090/sam/app.js
Error loading "can@2.3.0-pre.13#view/stache/system" at http://localhost:9090/node_modules/can/view/stache/system.js
$.buildFragment is not a function
    at Object.$.extend.buildFragment (http://localhost:9090/node_modules/can/util/jquery/jquery.js:46:12)
    at http://localhost:9090/node_modules/can/util/jquery/jquery.js:252:15
    at http://localhost:9090/node_modules/can/util/jquery/jquery.js:268:4
    at stealInstantiateResult.execute (http://localhost:9090/node_modules/steal/steal.js:5806:32)
    at linkDynamicModule (http://localhost:9090/node_modules/steal/steal.js:3547:32)
    at linkDynamicModule (http://localhost:9090/node_modules/steal/steal.js:3541:11)
    at linkDynamicModule (http://localhost:9090/node_modules/steal/steal.js:3541:11)
    at linkDynamicModule (http://localhost:9090/node_modules/steal/steal.js:3541:11)
    at link (http://localhost:9090/node_modules/steal/steal.js:3407:11)
    at Object.execute (http://localhost:9090/node_modules/steal/steal.js:3726:11)

Any help? What is that i am missing?

Thx

**Comment by darrindickey** [comment]
@satyagadepalli There are no errors with your install, just some warnings that some of the modules used by mySam are old and have been discontinued. However, they probably still work.

mysam --develop will start the app in develop mode. A couple of people have reported issues with running in develop mode, and not just in Windows.

mysam -s or mysam --server will start in server mode. See if the app runs there.

If the app is running, but will not return the weather to you, check a couple of things:
1. that the mysam-weather plugin is installed in the same node_modules directory as mysam. I found mine were being installed to the wrong node version folder.
2. that you are asking for the weather in one of the ways that mySam expects. I'm not sure how sensitive mySam is to input, but if it's expecting you to say, "Tell me the weather" and you say instead, "What is the weather like?", mySam may not respond. I don't know for sure, but it's a possibility.

I hope that helps.
